[package]
name = "rust-extend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "src/base",
    "src/actix-extend",
]

[dependencies]
"actix-extend" = { path = "./src/actix-extend" }